server:
  port: 10001
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.207.200:3340/mysql-master-slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
    slave-one:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.207.200:3350/mysql-master-slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
    slave-two:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.207.200:3360/mysql-master-slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xishanqu.slave.mapper
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true